name = "Migmatites"
uuid = "5167f344-0b18-48b9-9d08-769aea2eb5e3"
authors = ["scdyer <scdyer@uwaterloo.ca> and contributors"]
version = "0.0.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JPerpleX = "47cd544e-370f-4714-8b6c-e3a83d4a5076"
PetroBase = "b72d3798-c150-44c4-b6d4-c983c975f217"

[compat]
DocStringExtensions = "0.9.3"
PetroBase = "1.1.0"
julia = "1.6.7"
