name = "Migmatites"
uuid = "5167f344-0b18-48b9-9d08-769aea2eb5e3"
authors = ["scdyer <scdyer@uwaterloo.ca> and contributors"]
version = "0.0.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JPerpleX = "47cd544e-370f-4714-8b6c-e3a83d4a5076"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[compat]
DocStringExtensions = "0.9.3"
Optim = "1.9.4"
julia = "1.6.7"
